### PR TITLE
Emoji 13.1

### PR DESCRIPTION
**Pull request by C1710**
Yes, I'm very late with this one, 14.0 should be much faster (especially, since it's gotten a lot easier for me to build Twemoji).  

However, right now at least Blobmoji and Twemoji don't use the patched version for Android <7(?) compatibility... I'm currently testing whether that's still an issue

### CODE REVIEW

**Comment by C1710** [comment]
I just checked and it works without the patch on a virtual Android 5.0 device.

**Comment by C1710** [comment]
I might also update Blobmoji to Emoji/Unicode 14.0 directly, but the standard hasn't been officially released yet, so I'm not sure whether this is a good idea.

**Comment by connyduck** [comment]
Oh wow why did I not merge this yet? 😱 

It is still good to go, right? @C1710 

Btw, do you thing we can update the custom emojis to work with the new emoji2 library?

**Comment by C1710** [comment]
I think the current version of the library is already based on emoji2, but I'm not sure right now 😅

I haven't looked at it for a while, but I started working on a completely new emoji set picker, but I couldn't integrate it with the settings correctly yet.

And I think I'll have to check again whether the sets in this PR are actually still the current versions :D
(I think for Blobmoji it isn't, because I already released like 14.0.1 or something)

**Comment by C1710** [comment]
This is how the new version will look like:  
Screenshot of the new emoji picker in its own activity

Custom packs can simply be imported, without having to open up the system file explorer (some third party ones can't access the directory anymore on Android 11) and it supports more information, licenses, etc.  
Plus it's more organized 😅

**Comment by connyduck** [comment]
Oh cool 😍 

I merge this PR, ok?

**Pull request merged**
