### PR TITLE
Add privacy policy

### PR DESCRIPTION
**Pull request by connyduck**
Screenshot 2022-01-05 at 19 49 51

### CODE REVIEW

**Comment by tastytea** [comment]
Nitpick: The E-Mail URI should not have `//` in it, according to [RFC 6068](https://datatracker.ietf.org/doc/html/rfc6068#section-2).

**Comment by charlag** [comment]
Nice!
What about emoji downloads, anything about that?

**Comment by connyduck** [comment]
> What about emoji downloads, anything about that?

"The custom emoji sets that are downloadable in the preferences are hosted on Github pages"    ?

**Comment by charlag** [comment]
> > What about emoji downloads, anything about that?
> 
> "The custom emoji sets that are downloadable in the preferences are hosted on Github pages" ?

I don't know what it entails privacy-wise. Github Pages is Fastly and Cloudflare afaik.

**Comment by connyduck** [comment]
It's just a get request we are doing, there is no Cookie or anything sent along 🤔 
I'll leave it like it is for now

**Pull request merged**
