### PR TITLE
add Tutanota as sponsor

### PR DESCRIPTION
**Pull request by connyduck**
Screenshot 2023-07-07 at 18-00-41 Tusky - Mastodon client for Android

### CODE REVIEW

**Comment by charlag** [comment]
looks a bit too bold to me

**Comment by connyduck** [comment]
Should I make it a bit smaller?

**Comment by charlag** [comment]
yeah, at least smaller, maybe more to the bottom and maybe less contrast background? I could play with it but idk when I'll manage to yet :/

**Comment by connyduck** [comment]
I feel like when I make the background non-white it ruins Tutanotas branding :/
Will try smaller & more to the bottom.

**Comment by nikclayton** [comment]
> 2 Ideas:
>  

If we're voting, the second one gets my vote.

**Pull request merged**
