### PR TITLE
Use layout, rudimentary language switch

### PR DESCRIPTION
**Pull request by til**
Hi! https://tusky.app/faq/ and https://tusky.app/fr/faq/ look as intended so apparently the GitHub actions build step works. Here's a small followup to make all pages consistently use the default layout so that future modifications fit into the new templated structure provided by Jekyll. It also adds a rudimentary language switch to the bottom nav of the new FAQ pages.

Screenshot_20240425_001255

### CODE REVIEW

**Comment by til** [comment]
Also, not sure what you plans for the FAQs are, but I assume eventually the homepage should be changed to link to `/faq/` instead of the current `https://github.com/tuskyapp/faq/blob/master/README.md`.

**Review by connyduck — APPROVED** [review]
Thank you! Yes the homepage link should be changed now.

**Comment by til** [comment]
Would you like to add a link to the footer? Like this:

Screenshot_20240502_115339

If yes I'll add an icon of a question mark to the fontello font to make it look consistent.

**Comment by connyduck** [comment]
I'd just correct the link in the text, but an additional footer item is also ok.

**Pull request merged**
